let items = [];
const TELEGRAM_CHANNEL_URL = "https://t.me/+YepVltovdYJmMWQ1";
const REPO = "adhzxhh/teleconnect";
const grid = document.getElementById("contentGrid"), empty = document.getElementById("emptyState"), search = document.getElementById("searchInput"), filter = document.getElementById("categoryFilter"), editModal = document.getElementById("editModal"), editForm = document.getElementById("editForm");
let editingMessageId = "";

async function loadContent(){try{const r=await fetch(`content.json?ts=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();items=Array.isArray(d)?d:[]}catch(e){console.error("Could not load content.json:",e);items=[]}render()}
function formatDate(v){if(!v)return"";if(typeof v==="number")return new Date(v*1000).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"});return String(v)}
function cleanName(i){return String(i.filename||i.title||"").trim().replace(/\.[^.]+$/," ").replace(/[._\-]+/g," ").replace(/\s+/g," ").trim()}
function partInfo(item){
  // A manual edit is authoritative. part_disabled means the user explicitly
  // removed the part number, so filename guessing must never restore it.
  if(item.part_disabled===true)return null;
  if(item.part_group&&Number(item.part_number)>=1)return{key:String(item.part_group).trim().toLowerCase(),partNumber:Number(item.part_number),explicit:true};
  const name=String(item.filename||item.title||"").trim().replace(/\.[^.]+$/g,"");
  let m=name.match(/(?:^|[ ._\-])(?:part|pt)[ ._\-]?(\d+)$/i);
  if(m){const n=Number(m[1]);return n>=1?{key:name.slice(0,m.index).replace(/[._\-]+$/," ").trim().toLowerCase(),partNumber:n,explicit:true}:null}
  m=name.match(/(?:^|[ ._\-])\((\d+)\)$/);if(m){const n=Number(m[1]);if(n>=1){const base=name.slice(0,name.length-m[0].length).replace(/[._\-]+$/," ").trim();return{key:base.toLowerCase(),partNumber:n,explicit:true}}return null}
  // Do NOT guess generic numeric suffixes such as _10, -10 or x64.
  // They are commonly versions, architectures, model numbers, etc.
  return null;
}
function groupItems(source){const groups=[],eg=new Map(),ug=new Map();source.forEach(item=>{const info=partInfo(item);if(info){const key=`${String(item.category||"other").toLowerCase()}::${info.key}`;if(!eg.has(key)){const g={parts:[],first:item,partKey:info.key};eg.set(key,g);groups.push(g)}eg.get(key).parts.push({item,partNumber:info.partNumber});return}const fn=String(item.filename||item.title||"").trim().toLowerCase(),cat=String(item.category||"other").toLowerCase(),key=`${cat}::${fn}`;if(!ug.has(key))ug.set(key,[]);ug.get(key).push(item)});ug.forEach(list=>{if(list.length===1){groups.push({single:list[0]});return}const sorted=[...list].sort((a,b)=>Number(a.message_id||0)-Number(b.message_id||0));const ids=sorted.map(x=>Number(x.message_id)).filter(Number.isFinite),consecutive=ids.length===sorted.length&&(Math.max(...ids)-Math.min(...ids)<=sorted.length+2);if(consecutive)groups.push({parts:sorted.map((item,i)=>({item,partNumber:i+1})),first:sorted[0],partKey:cleanName(sorted[0]).toLowerCase()});else list.forEach(item=>groups.push({single:item}))});groups.forEach(g=>{if(g.parts)g.parts.sort((a,b)=>a.partNumber-b.partNumber)});groups.sort((a,b)=>Number(b.first?.date||b.single?.date||0)-Number(a.first?.date||a.single?.date||0));return groups}
function menu(item){return`<div class="card-menu"><button class="menu-trigger" type="button" aria-label="More options" aria-expanded="false">⋮</button><div class="menu-panel"><button class="menu-edit" type="button" data-edit-id="${escapeAttr(item.message_id)}">✏️ Edit</button></div></div>`}
function render(){const q=search.value.toLowerCase().trim(),cat=filter.value,filtered=items.filter(i=>{const c=String(i.category||"other").toLowerCase();return(cat==="all"||c===cat)&&(`${i.title||""} ${i.description||""} ${i.part_group||""}`).toLowerCase().includes(q)}),groups=groupItems(filtered);grid.innerHTML=groups.map(g=>g.single?renderSingle(g.single):renderGroup(g)).join("");empty.hidden=groups.length!==0}
function renderSingle(i){const type=String(i.type||"FILE").toUpperCase(),icon=i.icon||(type==="FILE"?"📦":type==="IMAGE"?"🖼️":"🎬"),url=i.url||TELEGRAM_CHANNEL_URL,du=i.download_url||"",action=du?`<a class="btn primary" href="${escapeAttr(du)}" download="${escapeAttr(i.filename||"")}">DOWNLOAD ↓</a>`:`<a class="btn primary" href="${escapeAttr(url)}" target="_blank" rel="noopener noreferrer">VIEW →</a>`;return`<article class="card"><div class="thumb">${menu(i)}<span class="badge">${escapeHtml(type)}</span><span>${escapeHtml(icon)}</span></div><div class="card-body"><h3>${escapeHtml(i.display_title||i.title||"Telegram file")}</h3><p>${escapeHtml(i.description||"")}</p><div class="card-footer"><span class="meta">${escapeHtml(formatDate(i.date))}</span>${action}</div></div></article>`}
function renderGroup(g){const f=g.first,count=g.parts.length,title=f.display_title||g.partKey.replace(/\b\w/g,c=>c.toUpperCase()),cat=String(f.category||"other").toUpperCase(),buttons=g.parts.map(({item,partNumber})=>{const u=item.download_url||item.url||TELEGRAM_CHANNEL_URL,label=item.download_url?`PART ${partNumber} ↓`:`PART ${partNumber} →`,attrs=item.download_url?`href="${escapeAttr(u)}" download="${escapeAttr(item.filename||"")}"`:`href="${escapeAttr(u)}" target="_blank" rel="noopener noreferrer"`;return`<a class="btn primary" ${attrs}>${label}</a>`}).join("");return`<article class="card multipart-card"><div class="thumb">${menu(f)}<span class="badge">${escapeHtml(cat)}</span><span>🧩</span></div><div class="card-body"><h3>${escapeHtml(title||"Multi-part file")}</h3><p>${count} parts · Select a part to download</p><div class="card-footer multipart-footer"><span class="meta">${escapeHtml(formatDate(f.date))}</span><div class="part-buttons">${buttons}</div></div></div></article>`}
function openEditor(messageId){const item=items.find(x=>String(x.message_id)===String(messageId));if(!item||!editModal)return;editingMessageId=String(item.message_id);const info=partInfo(item);document.getElementById("editTitle").value=item.display_title||item.title||"";document.getElementById("editDescription").value=item.description||"";document.getElementById("editCategory").value=String(item.category||"other").toLowerCase();document.getElementById("editPartGroup").value=item.part_group||"";document.getElementById("editPartNumber").value=item.part_disabled===true?"":(Number(item.part_number)>=1?item.part_number:(info?.partNumber||""));document.getElementById("editFilename").textContent=item.filename||item.title||"Telegram file";
  const group=info?.key?items.filter(x=>{const p=partInfo(x);return p&&p.key===info.key&&String(x.category||"other").toLowerCase()===String(item.category||"other").toLowerCase()}):[];
  const box=document.getElementById("editPartList");if(box){box.innerHTML="";if(group.length>1){box.innerHTML='<div class="edit-part-heading">Parts in this group</div>'+group.sort((a,b)=>(Number(partInfo(a)?.partNumber||999)-Number(partInfo(b)?.partNumber||999))).map(x=>`<label>${escapeHtml(x.filename||x.title||x.message_id)}<input class="edit-group-part" data-message-id="${escapeAttr(x.message_id)}" type="number" min="1" step="1" value="${Number(x.part_number)>=1?x.part_number:(partInfo(x)?.partNumber||"")}"></label>`).join("")} }
  editModal.hidden=false;document.body.classList.add("modal-open");setTimeout(()=>document.getElementById("editTitle")?.focus(),50)}
function closeEditor(){if(!editModal)return;editModal.hidden=true;editingMessageId="";document.body.classList.remove("modal-open")}
editForm?.addEventListener("submit",e=>{e.preventDefault();const item=items.find(x=>String(x.message_id)===editingMessageId);if(!item)return;const title=document.getElementById("editTitle").value.trim(),description=document.getElementById("editDescription").value.trim(),category=document.getElementById("editCategory").value.trim().toLowerCase()||"other",partGroup=document.getElementById("editPartGroup").value.trim(),partNumber=document.getElementById("editPartNumber").value.trim();if(partNumber&&(!/^\d+$/.test(partNumber)||Number(partNumber)<1)){alert("Part number must be 1 or greater.");return}const partInputs=[...document.querySelectorAll(".edit-group-part")];const parts=partInputs.map(x=>({message_id:x.dataset.messageId,part_number:x.value.trim()}));if(parts.some(x=>!/^\d+$/.test(x.part_number)||Number(x.part_number)<1)){alert("All multipart files must have a part number of 1 or greater.");return}const payload={message_id:item.message_id,title,description,category,part_group:partGroup,part_number:partNumber,part_number_changed:true,parts};const body=`SITE_EDIT\n\nEdit requested from the website.\n\n\`\`\`json\n${JSON.stringify(payload,null,2)}\n\`\`\``;window.open(`https://github.com/${REPO}/issues/new?title=${encodeURIComponent(`Edit site item ${item.message_id}`)}&body=${encodeURIComponent(body)}`,"_blank","noopener,noreferrer");closeEditor()});
document.addEventListener("click",e=>{const t=e.target.closest(".menu-trigger");if(t){const m=t.closest(".card-menu");document.querySelectorAll(".card-menu.open").forEach(x=>{if(x!==m)x.classList.remove("open")});m.classList.toggle("open");t.setAttribute("aria-expanded",m.classList.contains("open")?"true":"false");e.stopPropagation();return}const ed=e.target.closest("[data-edit-id]");if(ed){openEditor(ed.dataset.editId);ed.closest(".card-menu")?.classList.remove("open");return}if(e.target.closest("[data-close-edit]")||(editModal&&!editModal.hidden&&e.target===editModal)){closeEditor();return}if(!e.target.closest(".card-menu"))document.querySelectorAll(".card-menu.open").forEach(m=>m.classList.remove("open"))});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&editModal&&!editModal.hidden)closeEditor()});
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function escapeAttr(v){return String(v).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;")}
search.addEventListener("input",render);filter.addEventListener("change",render);document.getElementById("telegramButton").href=TELEGRAM_CHANNEL_URL;loadContent();